CREATE TABLE users (
    UserId INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    FullName VARCHAR(100) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    DateOfBirth DATE NULL,
    Gender VARCHAR(10) NULL,
    AvatarUrl VARCHAR(255) NULL,
    Role ENUM('User', 'Admin') DEFAULT 'User',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastLogin DATETIME NULL,
    IsActive BOOLEAN DEFAULT TRUE
);
CREATE TABLE posts (
    PostId INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    Title VARCHAR(200) NOT NULL,
    Content TEXT NOT NULL,
    ImageUrl VARCHAR(255) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL,
    Views INT DEFAULT 0,
    IsPublished BOOLEAN DEFAULT TRUE,
    IsDeleted BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_post_user FOREIGN KEY (UserId) REFERENCES users(UserId)
        ON DELETE CASCADE
);
CREATE TABLE comments (
    CommentId INT AUTO_INCREMENT PRIMARY KEY,
    PostId INT NOT NULL,
    UserId INT NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_comment_post FOREIGN KEY (PostId) REFERENCES posts(PostId)
        ON DELETE CASCADE,
    CONSTRAINT fk_comment_user FOREIGN KEY (UserId) REFERENCES users(UserId)
        ON DELETE CASCADE
);
